main:
  - name: 首页
    url: /
    weight: 10
  - name: 个人概述
    url: /#about
    weight: 20
  - name: 教育与项目
    url: /#experience
    weight: 30
  - name: 专业能力
    url: /#skills
    weight: 40
  - name: 荣誉奖项
    url: /#awards
    weight: 50
  - name: 下载简历
    url: /uploads/resume.pdf
    weight: 60
